### ISSUE TITLE
Compatibility with haven?

### ISSUE THREAD

**Issue by briatte** [leeper/lookfor#1]
The package does not seem to work when the data are imported with `haven` instead of `foreign`.

It's a shame, because `haven` never developed a function that mimicks Stata's `lookfor`:

https://github.com/tidyverse/haven/issues/237

I wrote my own equivalent of `lookfor` for another package:

https://github.com/juba/questionr/blob/master/R/lookfor.R

… and would gladly work on making your package compatible with `haven` if you feel that it's too much work on your end.

Poking @cschwem2er, who opened the first issue mentioned above.

**Comment by leeper** [comment]
This was a pet project a while back and I am not maintaining it. If you want to take the code and do something with it, go for it.
